### ISSUE TITLE
Feature request: Fadeout timer speed setting

### ISSUE THREAD

**Issue by sjn** [jgibbon/slumber#8]
Hei.

I think that the "Fade out when falling asleep" feature is very nice, but it is too fast. Can you add a settings feature that lets me set a custom delay? At the moment it starts fading "ca the last 10 seconds of the timer", and I'd like to try some different numbers. (e.g. a fadeout for the last 30 seconds or 2 minutes)

Thanks.

**Comment by jgibbon** [comment]
Took a long time (sorry, needed to rewrite basically everything), but this feature is now implemented and in testing. ;)

**Comment by sjn** [comment]
If you want me to test, feel free to ping me :)

**Comment by jgibbon** [comment]
Oh yeah, since almost everything was updated in one way or another, further testing (of basically any feature you care to invest time for) would be really appreciated :)
You can find an auto-generated pre-release at https://github.com/jgibbon/slumber/releases/tag/pre-0.13-3

Thanks in advance!

**Comment by jgibbon** [comment]
The new release is now out on openrepos and as a release build here on github.
Thanks for the feature request, it really feels better this way!

cheers
